### ISSUE TITLE
README.md checklist

### ISSUE THREAD

**Issue by wipegup** [copilotroadtrip/CoPilotBackend#5]
- [x] Introduction
- [x] Link to production
- [x] Link to TravisCI build
- [x] Team members w/ Github links
- [x] Add API Documentation Tool
- [x] DB schema
